import detectEthereumProvider from "@metamask/detect-provider";
import Head from "next/head";
import React from "react";
import BuyLoopToken from "../../component/BuyToken/BuyLoopToken";
interface Props {}
const BuyToken: React.FunctionComponent<Props> = () => {
  return (
    <div>
      <Head>
        <title>Buy Token</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        <BuyLoopToken />
      </div>
    </div>
  );
};

export default BuyToken;
