export const ErrorTypes = {
  //META MASK ERROR
  META_MASK_NOT_INSTALL: "META_MASK_NOT_INSTALL",
  META_MASK_CONNECTION_REJECTED: "META_MASK_CONNECTION_REJECTED",
  META_MASK_USER_DENIED_TRANSACTION: "META_MASK_USER_DENIED_TRANSACTION",
};
